#!/bin/bash
#SBATCH --job-name=gaussian-wild-seg
#SBATCH --output=logs/%x_%j.out
#SBATCH --time=4:00:00
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6

SCENE_NAME="figurines_varied"

SCRIPT_DIR=$SLURM_SUBMIT_DIR

DATASET_DIR="/scratch-shared/gpuuva074/datasets${SCENE_NAME}"
OUTPUT_PATH=${SCRIPT_DIR}/outputs/${SCENE_NAME}_seg

ITERATIONS=70000

mkdir -p "${SCRIPT_DIR}/logs"

echo "Activating gsw environment..."
. "${HOME}/Appearance-Invariant-Gaussian-Grouping/env_scripts/activate_gsw.sh" || exit

cd "$SCRIPT_DIR" || exit

python train.py \
    --source_path "$DATASET_DIR" \
    --scene_name ${SCENE_NAME} \
    --model_path "$OUTPUT_PATH" \
    --eval \
    --resolution 2 \
    --iterations $ITERATIONS \
    --object_path "$DATASET_DIR/object_mask"
