#!/bin/bash
#SBATCH --job-name=Stage-1-combined
#SBATCH --output=logs/%x_%j.out
#SBATCH --time=20:00:00
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --constraint=scratch-node

SCENES=("figurines" "figurines_varied" "ramen" "ramen_varied" "teatime" "teatime_varied")

SCRIPT_DIR=$SLURM_SUBMIT_DIR

cp -r "/scratch-shared/gpuuva074/datasets/" "${TMPDIR}"

ITERATIONS=70000

mkdir -p "${SCRIPT_DIR}/logs"

echo "Activating gsw environment..."
. "${HOME}/Appearance-Invariant-Gaussian-Grouping/env_scripts/activate_gsw_combined.sh" || exit

cd "$SCRIPT_DIR" || exit

for scene in "${SCENES[@]}"; do
    DATASET_DIR="${TMPDIR}/datasets/${scene}"
    OUTPUT_PATH=${SCRIPT_DIR}/outputs/${scene}_seg

    python train.py \
        --source_path "$DATASET_DIR" \
        --scene_name ${scene} \
        --model_path "$OUTPUT_PATH" \
        --eval \
        --resolution 2 \
        --iterations $ITERATIONS \
        --object_path "$DATASET_DIR/object_mask"
done
