#!/bin/bash
#SBATCH --job-name=stage2-grouping
#SBATCH --output=logs/%x_%j.out
#SBATCH --time=8:00:00
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6

SCRIPT_DIR=$SLURM_SUBMIT_DIR

mkdir -p "${SCRIPT_DIR}/logs"

cd "$SCRIPT_DIR" || exit

echo "Activating gg environment..."
. "${HOME}/Appearance-Invariant-Gaussian-Grouping/env_scripts/activate_gg.sh" || exit

python create_grouping_embeddings.py
