#!/bin/bash
#SBATCH --job-name=stage3-render
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --time=1:00:00
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6

SCENES=(figurines figurines_varied ramen ramen_varied teatime teatime_varied)
SCENE=${SCENES[$SLURM_ARRAY_TASK_ID]}

SCRIPT_DIR=$SLURM_SUBMIT_DIR

mkdir -p "${SCRIPT_DIR}/logs"

cd "$SCRIPT_DIR" || exit

echo "Activating gg environment..."
. "${HOME}/Appearance-Invariant-Gaussian-Grouping/env_scripts/activate_gg.sh" || exit

echo "Rendering scene: ${SCENE}"

python render.py \
    -m "output/${SCENE}" \
    --skip_train
