#!/bin/bash
#SBATCH --job-name=stage3-grouping
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --time=8:00:00
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --array=0-5

SCENES=(figurines figurines_varied ramen ramen_varied teatime teatime_varied)
SCENE=${SCENES[$SLURM_ARRAY_TASK_ID]}

DATASETS_ROOT=/scratch-shared/gpuuva074/datasets
SCRIPT_DIR=$SLURM_SUBMIT_DIR

mkdir -p "${SCRIPT_DIR}/logs"

cd "$SCRIPT_DIR" || exit

echo "Activating gg environment..."
. "${HOME}/Appearance-Invariant-Gaussian-Grouping/env_scripts/activate_gg.sh" || exit

echo "Training scene: ${SCENE}"

python train.py \
    -s "${DATASETS_ROOT}/${SCENE}" \
    -r 2 \
    -m "output/${SCENE}" \
    --config_file config_with_boundary.json

python render.py \
    -m "output/${SCENE}"
